const products = [
    {
        _id: "1",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "5",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 4.5,
        numReviews: 8,
    },
    {
        _id: "2",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "5",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 4.5,
        numReviews: 8,
    },
    {
        _id: "3",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "5",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 4.5,
        numReviews: 8,
    },
    {
        _id: "4",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "5",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 4.5,
        numReviews: 8,
    },
    {
        _id: "5",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "5",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 4.5,
        numReviews: 8,
    },
    {
        _id: "6",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "5",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 4.5,
        numReviews: 8,
    },
    {
        _id: "7",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "5",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 4.5,
        numReviews: 8,
    },
    {
        _id: "8",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "5",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 4.5,
        numReviews: 8,
    },
]

export default products